# Generated by Django 4.1.7 on 2023-03-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailconfirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name="EmailConfirmation",
        ),
    ]
