# Generated by Django 4.1.7 on 2023-03-30 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revokedtoken",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время создания Токена"
            ),
        ),
        migrations.AlterField(
            model_name="revokedtoken",
            name="token",
            field=models.TextField(unique=True, verbose_name="Токен"),
        ),
        migrations.AlterField(
            model_name="revokedtoken",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Токен пользователя",
            ),
        ),
    ]
