# Generated by Django 4.1.7 on 2023-03-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentsRating", "0009_remove_apartmentsrating_address"),
        ("Apartment", "0003_address_alter_apartment_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
