# Generated by Django 4.1.7 on 2023-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0004_delete_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="name",
        ),
        migrations.AddField(
            model_name="apartment",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apartment",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apartment",
            name="street",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="apartment",
            name="zip_code",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apartment",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
