# Generated by Django 4.1.7 on 2023-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0006_remove_apartment_address_alter_apartment_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"verbose_name": "Квартира", "verbose_name_plural": "Квартиры"},
        ),
        migrations.AlterField(
            model_name="apartment",
            name="zip_code",
            field=models.CharField(max_length=20, verbose_name="Почтовый индекс"),
        ),
    ]
