# Generated by Django 4.1.7 on 2023-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0007_alter_apartment_options_alter_apartment_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="zip_code",
            field=models.CharField(
                help_text="Необязательно поле для заполнения",
                max_length=20,
                verbose_name="Почтовый индекс",
            ),
        ),
    ]
