# Generated by Django 4.1.7 on 2023-03-31 12:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0010_alter_apartment_city_alter_apartment_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="category",
            field=models.CharField(
                default="",
                help_text="Люкс,элитка,эконом",
                max_length=255,
                verbose_name="Категория жилья",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="comfort",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("wi-fi", "Wi-Fi"),
                    ("shower", "Душевая кабина"),
                    ("doorphone", "Домофон"),
                    ("parking", "Парковка"),
                    ("tv", "Телевизор"),
                    ("appliances", "Бытовая техника"),
                    ("ac", "Кондиционер"),
                    ("bedding", "Постельное белье"),
                ],
                default="",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="description",
            field=models.TextField(
                default="", help_text="Опишите максимально", verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="floor",
            field=models.IntegerField(
                default=1,
                help_text="на каком этаже находится ваша квартира",
                verbose_name="Этаж",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="images",
            field=models.ImageField(
                default="default.jpg", upload_to="", verbose_name="Фотографии"
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="number_of_beds",
            field=models.IntegerField(
                default=0,
                help_text="количество спальных мест в квартире",
                verbose_name="Количество мест",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Напишите вашу цену",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="rooms",
            field=models.IntegerField(
                default=0,
                help_text="напишите кол-во комнат",
                verbose_name="Количество комнат",
            ),
        ),
    ]
