# Generated by Django 4.1.7 on 2023-03-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0015_alter_apartment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="images",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                upload_to="apartment_images",
                verbose_name="Фотографии",
            ),
        ),
    ]
