# Generated by Django 4.1.7 on 2023-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorites",
            name="favorites",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
