# Generated by Django 4.1.7 on 2023-03-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0002_favorites_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorites",
            old_name="apartments",
            new_name="apartment",
        ),
    ]
