# Generated by Django 4.1.7 on 2023-04-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0016_alter_apartment_images"),
        ("favorites", "0003_rename_apartments_favorites_apartment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorites",
            name="apartment",
        ),
        migrations.AddField(
            model_name="favorites",
            name="apartment",
            field=models.ManyToManyField(
                related_name="favorites", to="Apartment.apartment"
            ),
        ),
    ]
