# Generated by Django 4.1.7 on 2023-04-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0016_alter_apartment_images"),
        ("favorites", "0004_remove_favorites_apartment_favorites_apartment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorites",
            name="apartment",
        ),
        migrations.AddField(
            model_name="favorites",
            name="apartment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Apartment.apartment",
            ),
            preserve_default=False,
        ),
    ]
