# Generated by Django 4.1.7 on 2023-04-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0016_alter_apartment_images"),
        ("favorites", "0005_remove_favorites_apartment_favorites_apartment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorites",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="favorites",
            name="favorites",
        ),
        migrations.AddField(
            model_name="favorites",
            name="apartments",
            field=models.ManyToManyField(
                related_name="favorites", to="Apartment.apartment"
            ),
        ),
        migrations.AddField(
            model_name="favorites",
            name="comment",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="favorites",
            name="is_favorite",
            field=models.BooleanField(default=True),
        ),
    ]
