# Generated by Django 4.1.7 on 2023-04-01 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0016_alter_apartment_images"),
        ("favorites", "0006_remove_favorites_apartment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorites",
            name="apartments",
        ),
        migrations.RemoveField(
            model_name="favorites",
            name="comment",
        ),
        migrations.AddField(
            model_name="favorites",
            name="apartment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Apartment.apartment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favorites",
            name="favorites",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="favorites",
            name="is_favorite",
            field=models.BooleanField(default=True, verbose_name="избранное"),
        ),
    ]
