# Generated by Django 4.1.7 on 2023-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApartmentsRating",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.FloatField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
