# Generated by Django 4.1.7 on 2023-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentsRating", "0002_remove_apartmentsrating_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartmentsrating",
            options={
                "verbose_name": "Оценка апартамента",
                "verbose_name_plural": "Оценки апартаментов",
            },
        ),
        migrations.AlterField(
            model_name="apartmentsrating",
            name="rating",
            field=models.FloatField(
                help_text="Введите рейтинг от 1.0 до 5.0, например, 3.5",
                verbose_name="оценка",
            ),
        ),
    ]
