# Generated by Django 4.1.7 on 2023-03-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0001_initial"),
        ("ApartmentsRating", "0004_alter_apartmentsrating_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartmentsrating",
            options={
                "verbose_name": "Оценка апартамента",
                "verbose_name_plural": "Оценки апартаментов",
            },
        ),
        migrations.AddField(
            model_name="apartmentsrating",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Apartment.apartment",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentsrating",
            name="rating",
            field=models.FloatField(
                help_text="Введите рейтинг от 1.0 до 5.0, например, 3.5",
                verbose_name="оценка",
            ),
        ),
    ]
