# Generated by Django 4.1.7 on 2023-03-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0003_address_alter_apartment_address"),
        ("ApartmentsRating", "0007_alter_apartmentsrating_apartment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentsrating",
            name="address",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Apartment.address",
            ),
            preserve_default=False,
        ),
    ]
