# Generated by Django 4.1.7 on 2023-03-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentsRating", "0008_apartmentsrating_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartmentsrating",
            name="address",
        ),
    ]
