# Generated by Django 4.1.7 on 2023-03-30 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Apartment", "0006_remove_apartment_address_alter_apartment_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ApartmentsRating", "0009_remove_apartmentsrating_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentsrating",
            name="apartment",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Apartment.apartment",
                verbose_name="Квартира",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentsrating",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
