# Generated by Django 4.1.7 on 2023-03-30 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Apartment", "0010_alter_apartment_city_alter_apartment_state_and_more"),
        ("ApartmentsRating", "0011_alter_apartmentsrating_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentsrating",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Apartment.apartment",
                verbose_name="Квартира",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentsrating",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
