# Generated by Django 4.1.7 on 2023-03-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentsRating", "0013_alter_apartmentsrating_apartment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentsrating",
            name="rating2",
            field=models.FloatField(
                default=1,
                help_text="Введите рейтинг от 1.0 до 5.0, например, 3.5",
                verbose_name="оценка",
            ),
            preserve_default=False,
        ),
    ]
