# Generated by Django 4.1.7 on 2023-03-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentsRating", "0014_apartmentsrating_rating2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartmentsrating",
            name="rating2",
        ),
    ]
