# Generated by Django 4.1.7 on 2023-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentsRating", "0015_remove_apartmentsrating_rating2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentsrating",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
