# Generated by Django 4.1.7 on 2023-03-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentsRating", "0016_alter_apartmentsrating_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartmentsrating",
            old_name="apartment",
            new_name="address",
        ),
    ]
