# Generated by Django 4.1.7 on 2023-03-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentsRating", "0017_rename_apartment_apartmentsrating_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartmentsrating",
            old_name="address",
            new_name="apartment",
        ),
    ]
